[package]
name = "cloudflare-webui"
version = "0.1.0"
authors = ["Thomas Dy <thatsmydoing@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.0"
url = "0.5.0"

[dependencies.hyper]
version = "0.8.0"
default-features = false
